version: '3.8'

services:
  # Backend Mock API Server
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "3000:3000"
    networks:
      - app-network
    restart: unless-stopped

  # Frontend Vue Application
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - api
    networks:
      - app-network
    restart: unless-stopped
    environment:
      - API_URL=http://api:3000

networks:
  app-network:
    driver: bridge

